#!/bin/bash

# 1. 创建数据目录并授权
# 2. 静默安装数据库（CDB或非CDB）
# 3. 配置并启动监听、配置网络文件
# 4. 配置OMF:DB_CREATE_FILE_DEST DB_RECOVERY_FILE_DEST
# 5. 数据库密码永不过期

source /etc/locale.conf
source /tmp/setenv.sh

mkdir -p ${ORACLE_DATAFILE} ${ORACLE_RECOVER_PATH}
chown -R oracle:oinstall ${ORACLE_DATAFILE}  ${ORACLE_RECOVER_PATH}


DBCA_FILE=${ORACLE_HOME}/assistants/dbca/dbca.rsp

oracle_dbca(){

# 静默方式创建一个CDB数据库
#dbca -silent -ignorePreReqs -ignorePrereqFailure -createDatabase \
#-responseFile NO_VALUE \
#-templateName General_Purpose.dbc \
#-createAsContainerDatabase true \
#-numberOfPDBs 1 \
#-pdbName pdb1 \
#-pdbAdminPassword ${ORACLE_PASS_ALL} \
#-gdbname ${ORACLE_SID} -sid ${ORACLE_SID} \
#-sysPassword ${ORACLE_PASS_ALL} -systemPassword ${ORACLE_PASS_ALL} -dbsnmpPassword ${ORACLE_PASS_ALL} \
#-datafileDestination ${ORACLE_DATAFILE} \
#-characterset ${CHARACTERSET} \
#-totalMemory ${ORACLE_MEMLIT}

su - oracle <<EOF
source /home/oracle/.bash_profile

dbca -silent -ignorePreReqs -ignorePrereqFailure -createDatabase \
-responseFile NO_VALUE \
-templateName General_Purpose.dbc \
-gdbname ${ORACLE_SID} -sid ${ORACLE_SID} \
-sysPassword ${ORACLE_PASS_ALL} -systemPassword ${ORACLE_PASS_ALL} -dbsnmpPassword ${ORACLE_PASS_ALL} \
-datafileDestination ${ORACLE_DATAFILE} \
-characterset ${CHARACTERSET} \
-totalMemory ${ORACLE_MEMLIT}

#配置静态监听
cat <<LIS > ${ORACLE_HOME}/network/admin/listener.ora
# listener.ora Network Configuration File: ${ORACLE_HOME}network/admin/listener.ora
# Generated by Oracle configuration tools.

SID_LIST_LISTENER=
  (SID_LIST=
    (SID_DESC=
      (SID_NAME = ${ORACLE_SID})
      (ORACLE_HOME = ${ORACLE_HOME})
    )
  )

LISTENER=
  (DESCRIPTION=
    (ADDRESS_LIST=
      (ADDRESS=(PROTOCOL = tcp)(HOST = ${ORACLE_SYSIP})(PORT = ${ORACLE_PORT}))
    )
  )

ADR_BASE_LISTENER = ${ORACLE_BASE}
LIS

#配置静态TNS
cat <<TNS >${ORACLE_HOME}/network/admin/tnsnames.ora
# tnsnames.ora Network Configuration File: ${ORACLE_HOME}/network/admin/tnsnames.ora
# Generated by Oracle configuration tools.

${ORACLE_SID} =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = ${ORACLE_SYSIP})(PORT = ${ORACLE_PORT}))
    )
    (CONNECT_DATA =
      (SERVICE_NAME = ${ORACLE_SID})
      (SERVER = DEDICATED)
    )
  )

TNS


lsnrctl start

sqlplus -S / as sysdba <<PWUNLI
set heading off
set feedback off
set pagesize 0
set verify off
set echo off
ALTER SYSTEM SET DB_CREATE_FILE_DEST = '${ORACLE_DATAFILE}' scope=spfile;
ALTER SYSTEM SET DB_CREATE_ONLINE_LOG_DEST_1 = '${ORACLE_DATAFILE}' scope=spfile;
ALTER SYSTEM SET DB_RECOVERY_FILE_DEST_SIZE = 100G scope=spfile;
ALTER SYSTEM SET DB_RECOVERY_FILE_DEST = '${ORACLE_RECOVER_PATH}' scope=spfile;
ALTER SYSTEM SET LOG_ARCHIVE_DEST_1 = 'LOCATION=USE_DB_RECOVERY_FILE_DEST' scope=spfile;
alter profile default limit password_life_time unlimited;
shutdown immediate;
startup mount;
alter database archivelog;
alter database open;
exit
PWUNLI
EOF
} 

oracle_dbca

echo -e "\n\e[1;36m  Database instance creation completed！ \e[0m"
